/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_tmain */

#ifndef _Included_jni_tmain
#define _Included_jni_tmain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_tmain
 * Method:    no_args_return
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_tmain_no_1args_1return
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
